Revert "Update bg, include Bulgarian (enhanced) keyboard, proposed by group of 500 people in May 2020."
The commit and its follow-up commits fail the CI pipeline, see
https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/merge_requests/87

----------------------------- Captured stderr call -----------------------------
Error:            Error interpreting include file "bg"
                  Exiting
                  Abandoning symbols file "(null)"
Error:            symbols not defined in XkbWriteXKBSymbols
                  Output file "stdout" removed

Follow-up commits are:
  Revert "Update bg"
  Revert "Fixed one more error"
  Revert "Fixed errors "
  Revert "Update bg"

This reverts commit 0ce5ec0257aeb9285ad5ac3a1498d3753c9474c3.
This reverts commit ba3a79fc993fdf553a0e8ca0e8ad73bf46186ad6.
This reverts commit a1345c2bb5e866391b41f3a0863cb271a45a5a3e.
This reverts commit a7042d9c2ff23f74c8cf0d8a68fb669d206033b3.
This reverts commit a0f3bf064347ec344d6dde655c5f61782f591256.

Signed-off-by: Peter Hutterer <peter.hutterer@who-t.net>